/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uber;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author NITJ
 */
public class AddMoney extends javax.swing.JFrame {

    static String w1;
    
    /**
     * Creates new form AddMoney
     */
    public AddMoney() {
        initComponents();
        w1=Login.wall;
        Login.wa=1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        wallet = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter the amount to be added");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(24, 33, 280, 70);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 110, 80, 30);
        getContentPane().add(wallet);
        wallet.setBounds(270, 50, 90, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 230, 80, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uber/wallet.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-70, -30, 530, 320);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String s1=Login.userid;
            int n1,n2;
            n1=Integer.parseInt(wallet.getText());
            
        Class.forName("com.mysql.jdbc.Driver");
        //Connection obj1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/uber", "root", "");
          //  String query1="SELECT * FROM `users` WHERE UserId= '"+s1+"'";
           //PreparedStatement ps=(PreparedStatement) obj1.prepareStatement(query1);
           //ResultSet rs1=ps.executeQuery();
           //Class.forName("com.mysql.jdbc.Driver");
            Connection obj=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/uber", "root", "");
            String query="SELECT * FROM `users` WHERE  UserId = '"+s1+"'";
           PreparedStatement ps=(PreparedStatement) obj.prepareStatement(query);
           ResultSet rs=ps.executeQuery();
           if(rs.next())
           {
           n2=Integer.parseInt(rs.getString(6));
        Connection obj1=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/uber", "root", "");
           String query1="UPDATE `users` SET `Wallet`=? WHERE UserId= '"+s1+"'";
           PreparedStatement ps1=(PreparedStatement) obj1.prepareStatement(query1);
           ps1.setString(1,String.valueOf(n1+n2));
           ps1.executeUpdate();
           JOptionPane.showMessageDialog(rootPane,"Done");
           w1=String.valueOf(n1+n2);
           this.setVisible(false);
                new Login1().setVisible(true);
           }
                } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"please enter an integer");
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
                new Login1().setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMoney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField wallet;
    // End of variables declaration//GEN-END:variables
}
