/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uber;

import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author NITJ
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        done = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pass2 = new javax.swing.JPasswordField();
        pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        bu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 100, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ph No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 80, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 100, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("User Id");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 110, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 120, 60));

        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 190, 40));
        getContentPane().add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 190, 40));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 190, 40));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 190, 40));

        done.setBackground(new java.awt.Color(0, 0, 255));
        done.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        done.setForeground(new java.awt.Color(255, 255, 255));
        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        getContentPane().add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 130, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Confirm Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 140, 50));
        getContentPane().add(pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 190, 40));

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 190, 40));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 80, 40));

        bu.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        bu.setText("Show password");
        bu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buActionPerformed(evt);
            }
        });
        getContentPane().add(bu, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Welcome New User!");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 270, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uber/1.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
    try {  
        int k=0;
           Class.forName("com.mysql.jdbc.Driver");
           Connection obj=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/uber", "root", "");
           String query="INSERT INTO `users`(`Name`, `PhNo`, `Email`, `UserId`,`Password`) VALUES (?,?,?,?,?);";
           PreparedStatement ps=(PreparedStatement) obj.prepareStatement(query);
           java.sql.Connection obj1=(java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/uber", "root", "");
            String query1="SELECT * FROM `users` WHERE  UserId = '"+id.getText()+"'";
           PreparedStatement ps1=(PreparedStatement) obj1.prepareStatement(query1);
           ResultSet rs1=ps1.executeQuery();
           if(!rs1.next())
           {
           if((Arrays.toString(pass.getPassword())).equals((Arrays.toString(pass2.getPassword()))))
           {
               if(name.getText().equals(""))
               {
                   JOptionPane.showMessageDialog(rootPane,"Please enter name");
                   k=1;
               }
               
               if(no.getText().equals(""))
               {
                   JOptionPane.showMessageDialog(rootPane,"Please enter Phone Number");
                   k=1;
               }
               if(email.getText().equals(""))
               {
                   JOptionPane.showMessageDialog(rootPane,"Please enter Email Id");
                   k=1;
               }
               if(id.getText().equals(""))
               {
                   JOptionPane.showMessageDialog(rootPane,"Please enter Email Id");
                   k=1;
               }
               if(k==0)
               {
                   if(no.getText().length()!=10)
                       JOptionPane.showMessageDialog(rootPane,"Please enter a valid number of 10 digits");
                       else
                   {
                       int j1=pass.getText().length();
                       if(j1>=3&&j1<=20)
                       {
                       String o=no.getText();int y=0;
                       for(int i=0;i<10;i++)
                       {
                           if(o.charAt(i)>=48&&o.charAt(i)<=57)
                           y++;
                       }
                       if(y==10)
                       {
           ps.setString(1,name.getText());
           ps.setString(2,no.getText());
           ps.setString(3,email.getText());
           ps.setString(4,id.getText());        
           ps.setString(5,pass.getText());
              this.setVisible(false);
              new Login().setVisible(true);
           ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane,"Done");
           }
            else
                     JOptionPane.showMessageDialog(rootPane,"Please enter a valid number");      
                   }
                       else
                           JOptionPane.showMessageDialog(rootPane,"Please enter password of legth between 3 to 20"); 
               }
               }   
           }
           else
           {
               JOptionPane.showMessageDialog(rootPane,"Password doesnt match");
           }
           }
           else
               JOptionPane.showMessageDialog(rootPane,"This username already exists. Please enter some other username");
       } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Error"+ex.getMessage());
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_doneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
            new Login().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buActionPerformed
        if(bu.isSelected())
        {
        pass.setEchoChar((char)0);
pass2.setEchoChar((char)0);
        }
if(!bu.isSelected())
        {
        pass.setEchoChar((char)9733);
pass2.setEchoChar((char)9733);
        }// TODO add your handling code here:
    }//GEN-LAST:event_buActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        // TODO add your handling code here:
        if(name.getText().trim().toLowerCase().equals("Name"))
        {
            name.setText("");
            name.setForeground(Color.black);
// TODO add your handling code here:
        }// TODO a
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
        if(name.getText().trim().toLowerCase().equals("User id")||name.getText().equals(""))
        {
            name.setText("Name");
            name.setForeground(Color.gray);
// TODO add your handling code here:
        }// TODO a
    }//GEN-LAST:event_nameFocusLost

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bu;
    private javax.swing.JButton done;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField no;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pass2;
    private javax.swing.JTextField password;
    // End of variables declaration//GEN-END:variables
}
